# Generated by Django 4.1.13 on 2026-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Назва деталі')),
                ('category', models.CharField(max_length=150, verbose_name='Категорія')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.IntegerField(default=0, verbose_name='Поточний залишок')),
                ('min_quantity', models.IntegerField(default=2, verbose_name='Критичний мінімум')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місце на складі (Стелаж/Полиця)')),
            ],
        ),
    ]
